# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(max_length=200, unique=True)),
                ('remarks', models.CharField(max_length=200)),
                ('note', models.TextField()),
            ],
        ),
    ]
