# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'FEMALE')], max_length=200)),
                ('mobile_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 639XXXXXXXXXX.', regex='^+\\b(639)\\d{9}?\\b$')])),
                ('email_address', models.EmailField(blank=True, max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
            ],
        ),
    ]
