# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=200, unique=True)),
                ('remark', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_issue', to='maintenance.Issue')),
            ],
        ),
        migrations.AlterField(
            model_name='representative',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='Male', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_repr', to='maintenance.Representative'),
        ),
    ]
