# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20160929_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='reference_number',
        ),
    ]
