# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20160928_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='mobile_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 09XXXXXXXXXX.', regex='^\\b(09)\\d{9}?\\b$')]),
        ),
    ]
