# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20160929_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reference_id',
            field=models.CharField(default='#0000', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
