# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20160929_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_repository', to='maintenance.Issue')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_repository', to='maintenance.Ticket')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
    ]
