# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0006_auto_20160929_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='representative',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_repr', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
