# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20160929_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 09XXXXXXXXXX.', regex='^\\b(09)\\d{9}?\\b$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid input.', regex='^[a-zA-Z\\xd1\\xf1\\s.-]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid input.', regex='^[a-zA-Z\\xd1\\xf1\\s.-]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid input.', regex='^[a-zA-Z\\xd1\\xf1\\s.-]*$')]),
        ),
    ]
