# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20170125_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
