# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reference_number',
            field=models.CharField(default='#00000', max_length=200, unique=True),
        ),
    ]
