# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_issue_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='record.Issue')),
            ],
        ),
        migrations.RemoveField(
            model_name='repository',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='issue',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
