# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20170129_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_created', to='record.User'),
        ),
    ]
