# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_issue_reference_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='reference_number',
            new_name='reference_id',
        ),
        migrations.AlterField(
            model_name='issue',
            name='reference_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
