# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20170129_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
