# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ISSUE', 'Issue'), ('THREAD', 'Thread')], default='ISSUE', max_length=200),
        ),
    ]
