# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], max_length=200)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
