# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_smsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('EMPLOYEE', 'Employee')], max_length=200),
        ),
    ]
