# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_user_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
