# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20170226_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tracker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='record.Tracker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='remark',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SLEEP', 'Sleep'), ('DEAD', 'Dead')], default='OPEN', max_length=200),
        ),
    ]
