# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_auto_20170226_1129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together=set([('name', 'company')]),
        ),
    ]
