# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20160929_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'NORMAL'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remark',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=200),
        ),
    ]
