# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_auto_20170226_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='remark',
            new_name='decision',
        ),
    ]
