# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_auto_20170226_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='record.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
