# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_auto_20170307_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[(None, ''), ('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default=None, max_length=200, null=True),
        ),
    ]
