# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_auto_20170307_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
