# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_auto_20161202_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'User')], default='ADMIN', max_length=200),
            preserve_default=False,
        ),
    ]
