# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 04:02
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_auto_20170307_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10, null=True),
        ),
    ]
