# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='record.User'),
        ),
    ]
