# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_thread_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
