# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_tracker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
